package:
  name: obspy
  version: "0.10.1"

source:
  fn: obspy-0.10.1.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-0.10.1.zip
  md5: 0d32bcf8e9534d32c91efee84291bad3

build:
  number: 1
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy <1.0.0
    - argparse # [py26]
    - flake8
  run:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy <1.0.0
    - argparse # [py26]
    - flake8

test:
  # Python imports
  imports:
    - obspy
    - obspy.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
