language: c

os:
  - linux
  - osx

env:
  matrix:
    - CONDA_PY=26
    - CONDA_PY=27
    - CONDA_PY=33
    - CONDA_PY=34

  global:
    - secure: "COVdFxDnyNRNJrDyPQJA6jA91sFEfR2OJhpBHOKprVb40AJ8tO0mwYh3Vrx+xjp/8OKeaflP7lcIYUITb98V/dgLV7BDeNrF5wW9A4lrqjwfG0DEW8zcfQwSljHzCIrw+RVg7FegOZjmEDG1wUF39z6q+7/mB9MFqatB8WYJW18="

install:
  - source continuous-integration/travis/install_$TRAVIS_OS_NAME.sh

script:
  - conda build obspy-0.10.0rc1

after_success:
  - python continuous-integration/move-conda-package.py obspy-0.10.0rc1
  - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2 --channel travis
