# file not up to date concerning release versions as we currently don't build packages in Travis
language: c

os:
  - linux
  - osx

env:
  matrix:
    - CONDA_PY=26
    - CONDA_PY=27
    - CONDA_PY=33
    - CONDA_PY=34

  global:
    - secure: "d3CTKzK4q+6tomK4DT0bCIloMw9uBcNk6CZMh604cDUkvQ6mKSo77wOrHhw1YMuTdbT1lSGo0T4IvC/DSFb6UemZ9AbXEiK3YZ+CmfSV2VVfKRjCLIkDecKQXjL05nk55xtsZXIOvvas/eOWifn/LS/dNY+a6fERpQwv3jbmmJk="

install:
  - source continuous-integration/travis/install_$TRAVIS_OS_NAME.sh

script:
  - conda build obspy-0.10.0rc1

after_success:
  - python continuous-integration/move-conda-package.py obspy-0.10.0rc1
  - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2 --channel travis
