package:
  name: obspy
  version: "0.10.0"

source:
  fn: obspy-0.10.0.tar.gz
  url: https://github.com/obspy/obspy/archive/0.10.0.tar.gz

build:
  number: 0
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8
  run:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8

test:
  # Python imports
  imports:
    - obspy
    - obspy.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
