package:
  name: obspy
  version: "0.10.2"

source:
  fn: obspy-0.10.2.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-0.10.2.zip
  md5: 7a77c6b96143e6758c38fed0775d2b16

build:
  number: 0
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8
  run:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8

test:
  # Python imports
  imports:
    - obspy
    - obspy.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
