package:
  name: obspy
  version: "1.0.0"

source:
  fn: obspy-1.0.0.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-1.0.0.zip
  md5: 40925691d3b0eaeac39b0513c46cf306

build:
  number: 0
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8
    - requests
    - decorator
  run:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8
    - requests
    - decorator
test:
  # Python imports
  imports:
    - obspy
    - obspy.io.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
